import AsyncStorage from '@react-native-async-storage/async-storage';
import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import { create } from 'zustand';

/**
 * Sound effects for the celebration moments. The clips are generated by
 * `scripts/gen-sfx.mjs` — re-run it after editing the note lists there.
 *
 * Players are created once and reused: creating one per play adds audible
 * latency, which defeats the point of feedback.
 */

const SOURCES = {
  tap: require('../../assets/sfx/tap.wav'),
  checkin: require('../../assets/sfx/checkin.wav'),
  levelup: require('../../assets/sfx/levelup.wav'),
  badge: require('../../assets/sfx/badge.wav'),
  coin: require('../../assets/sfx/coin.wav'),
};

export type SfxName = keyof typeof SOURCES;

/** Mixed by ear against each other — the fanfare would bully the rest at 1.0. */
const VOLUME: Record<SfxName, number> = {
  tap: 0.35,
  checkin: 0.75,
  levelup: 0.85,
  badge: 0.8,
  coin: 0.6,
};

const KEY = 'levla.sfx.enabled';
const players: Partial<Record<SfxName, AudioPlayer>> = {};

type SfxState = {
  enabled: boolean;
  setEnabled: (on: boolean) => void;
};

export const useSfxStore = create<SfxState>((set) => ({
  enabled: true,
  setEnabled: (on) => {
    set({ enabled: on });
    AsyncStorage.setItem(KEY, on ? 'on' : 'off').catch(() => {});
  },
}));

function player(name: SfxName): AudioPlayer | null {
  try {
    if (!players[name]) {
      const p = createAudioPlayer(SOURCES[name]);
      p.volume = VOLUME[name];
      players[name] = p;
    }
    return players[name] ?? null;
  } catch {
    return null;
  }
}

/**
 * Load the saved preference and warm up the players. Safe to call more than
 * once; failures are swallowed because sound is never worth crashing over.
 */
export async function initSfx(): Promise<void> {
  try {
    const raw = await AsyncStorage.getItem(KEY);
    if (raw === 'off') useSfxStore.setState({ enabled: false });

    // 'mixWithOthers' keeps whatever the youth is listening to playing, and
    // playsInSilentMode:false means the iOS ringer switch still wins.
    await setAudioModeAsync({
      playsInSilentMode: false,
      shouldPlayInBackground: false,
      interruptionMode: 'mixWithOthers',
    });

    (Object.keys(SOURCES) as SfxName[]).forEach(player);
  } catch {
    // No sound is an acceptable outcome; the app carries on.
  }
}

/** Fire-and-forget. Silent when the member has turned sound off. */
export function playSfx(name: SfxName): void {
  if (!useSfxStore.getState().enabled) return;
  const p = player(name);
  if (!p) return;
  // expo-audio doesn't rewind after playback finishes, unlike expo-av.
  p.seekTo(0)
    .then(() => p.play())
    .catch(() => {});
}
